# Generated by Django 5.0.7 on 2024-08-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
