# Generated by Django 5.0.7 on 2024-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
