# Generated by Django 5.0.7 on 2024-08-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='websitelink',
        ),
        migrations.AddField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='title',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='website_link',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
